#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

[ -f "$XDG_CONFIG_HOME"/X11/xresources ] && xrdb -merge "$XDG_CONFIG_HOME"/X11/xresources

dunst &
nm-applet &
blueman-applet &
udiskie -Ns &
hsetroot -solid '#1d2021'
xmodmap "$XDG_CONFIG_HOME"/X11/xmodmap &
picom --dbus &
unclutter --timeout 1 --ignore-scrolling &
xrandr --dpi 120
redshift-gtk &
( sleep 5 && jellyfin-mpv-shim ) &
caffeine &
dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

if [ "${0#*/.nvidia-xinitrc}" != "$0" ]; then
    mons -e bottom
    nvidia-settings --assign CurrentMetaMode="1920x1080 +0+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"
elif [ "$(xrandr | grep -c ' connected')" = "2" ]; then
    mons -e top
fi

exec i3
